@GENERATED_WARNING@
FROM python:@DOCKER_FROM_TAG@

MAINTAINER Paweł Tomulik <ptomulik@@meil.pw.edu.pl>

@DOCKER_SPHINX_ARGS@

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION

LABEL org.label-schema.build-date="${BUILD_DATE}" \
      org.label-schema.name="Docker Sphinx Image" \
      org.label-schema.description="Docker image with Sphinx documentation generator. Designed to build docs for Korowai project." \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/korowai/docker-sphinx" \
      org.label-schema.vendor="Paweł Tomulik" \
      org.label-schema.version="${VERSION}" \
      org.label-schema.schema-version="1.0"


@DOCKER_SPHINX_ENV@

RUN set -xe && \
    apk add --no-cache --update git doxygen && \
    python -m pip install -U pip && \
    python -m pip install -U virtualenv && \
    python -m pip install sphinx=="${SPHINX_VERSION}" \
                          sphinx-autobuild=="${SPHINX_AUTOBUILD_VERSION}" \
                          "git+https://github.com/readthedocs/sphinx_rtd_theme@@${SPHINX_RTD_THEME_VERSION}" \
                          "git+https://github.com/korowai/sphinx-php.git@@korowai" \
                          "git+https://github.com/breathe-doc/breathe@@${SPHINX_BREATHE_VERSION}" && \
   rm -rf ~/.cache/pip && \
   mkdir -p $KRW_CODE

COPY bin/* /usr/local/bin/

EXPOSE $SPHINX_AUTOBUILD_PORT

VOLUME $KRW_CODE
WORKDIR $KRW_CODE

ENTRYPOINT [ "sphinx-entrypoint" ]
CMD ["autobuild"]

# vim: ft=dockerfile:
